version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.1-node-browsers

    steps:
      - checkout
      - run:
          name: Environment Update
          command: sudo apt update && sudo apt-get update
      - run:
          name: Install Dependencies
          command: sudo docker-php-ext-install zip && sudo apt-get install unzip
      - run:
          name: Install jmeter
          command: wget -c http://apache.mirror.amaze.com.au//jmeter/binaries/apache-jmeter-5.2.1.zip && unzip apache-jmeter-5.2.1.zip
      - run:
          name: Test Set up
          command: sh apache-jmeter-5.2.1/bin/jmeter.sh -n -t store_setup.jmx
      - run:
          name: Install calibre
          command: sudo npm install -g calibre
      - run:
          name: Configure calibre environment
          command: calibre token set ${CALIBRE_API_TOKEN}
      - run:
          name: Update calibre profiles
          command: sh update_test_profiles.sh ${CHECKOUT_SITE_SLUG} "cookie-jar.txt"
      - run:
          name: Create Snapshot
          command: calibre site create-snapshot --site=${CHECKOUT_SITE_SLUG}
workflows:
  version: 2
  # Configuration to run the test every day at 11 a.m.
  nightly:
    triggers:
      - schedule:
          cron: "15 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build